name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Define explicitamente a versão do Ubuntu
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      # Publica a animação no branch `output`
      - name: Deploy Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist



  
